trigger:
  - main

pool:
  vmImage: 'windows-latest'

variables:
  frontend_dir: '$(Build.SourcesDirectory)/frontend'
  backend_dir: '$(Build.SourcesDirectory)/backend'
  python.version: '3.x'

steps:
  # ------------ Python Backend Setup ------------
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      addToPath: true
    displayName: 'Use Python $(python.version)'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    workingDirectory: $(backend_dir)
    displayName: 'Install Python backend dependencies'

  # ------------ Run Backend and Kill After 5 Seconds ------------
  - powershell: |
      cd "$(backend_dir)"

      Write-Output " Starting Uvicorn..."
      $proc = Start-Process "uvicorn" -ArgumentList "app.main:app", "--host", "127.0.0.1", "--port", "8000" `
               -PassThru `
               -RedirectStandardOutput "stdout.txt" `
               -RedirectStandardError "stderr.txt" `
               -NoNewWindow

      Start-Sleep -Seconds 5

      $stdout = Get-Content "stdout.txt" -Raw
      $stderr = Get-Content "stderr.txt" -Raw
      $output = $stdout + "`n" + $stderr

      if ($output -notmatch "Application startup complete") {
          Write-Output " Server failed to start."
          Write-Output $output
          Exit 1
      } else {
          Write-Output " Server started successfully. Killing process ID $($proc.Id)..."
          Stop-Process -Id $proc.Id -Force
      }
    displayName: 'Start backend, verify, and kill after 5 seconds'

  # ------------ Node Frontend Setup & Build ------------
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Set up Node.js'

  - script: |
      npm install
      npm run build
    workingDirectory: $(frontend_dir)
    displayName: 'Install and Build Frontend'

  # ------------ Optional: Frontend Tests ------------
  - script: npm run test
    workingDirectory: $(frontend_dir)
    displayName: 'Run Frontend Tests'
    condition: false

  # ------------ Optional: Backend Tests ------------
  - script: pytest
    workingDirectory: $(backend_dir)
    displayName: 'Run Backend Tests'
    condition: false
